name: Trigger Target Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: diggioorg02/worflowremote/.github/workflows/templateclienteowf.yml@main
    secrets:
      access-token: ${{ secrets.PAT }}
